import { Client } from "@notionhq/client";
import { NotionToMarkdown } from "notion-to-md";
import { getPageBySlug as getPageBySlugFromCurriculum } from "./curriculum";
import fs from "fs";
import path from "path";

const notion = new Client({ auth: process.env.NOTION_API_KEY });
const n2m = new NotionToMarkdown({ notionClient: notion });

// Load Cloudinary image map (generated by scripts/sync-images.mjs)
let imageMap: Record<string, string> = {};
try {
  const mapPath = path.join(process.cwd(), "src/lib/image-map.json");
  imageMap = JSON.parse(fs.readFileSync(mapPath, "utf-8"));
} catch {
  // image-map.json may not exist in dev mode; fall back to proxy
}

// Custom transformer for image blocks: use Cloudinary URL with proxy fallback
n2m.setCustomTransformer("image", async (block) => {
  const blockId = block.id;
  const url = imageMap[blockId] || `/api/notion-image?blockId=${blockId}`;
  return `![image](${url})`;
});


function stripCurriculumHeader(md: string): string {
  // Remove everything up to and including the last </details> block
  // These are the curriculum navigation blocks at the top of each Notion page
  const lastDetailsClose = md.lastIndexOf("</details>");
  if (lastDetailsClose !== -1) {
    return md.slice(lastDetailsClose + "</details>".length).trim();
  }
  // Fallback: remove common header patterns
  return md
    .replace(/^\*\*📓 커리큘럼\*\*\s*/m, "")
    .replace(/^---\s*/m, "")
    .replace(/^◻️\s*\[Main Page\].*\n?/m, "");
}

// In-memory cache for dev mode speed
const contentCache = new Map<string, { content: string; timestamp: number }>();
const CACHE_TTL = 5 * 60 * 1000; // 5 minutes

export async function getPageContent(pageId: string): Promise<string> {
  const cached = contentCache.get(pageId);
  if (cached && Date.now() - cached.timestamp < CACHE_TTL) {
    return cached.content;
  }

  const mdBlocks = await n2m.pageToMarkdown(pageId);
  const mdString = n2m.toMarkdownString(mdBlocks);
  const stripped = stripCurriculumHeader(mdString.parent);
  // Remove double quotes wrapping blockquote lines (notion-to-md callout artifact)
  const content = stripped.replace(/^(>+\s*)"(.+)"$/gm, "$1$2");

  contentCache.set(pageId, { content, timestamp: Date.now() });
  return content;
}

export async function getPageContentBySlug(
  slug: string
): Promise<{ title: string; content: string } | null> {
  const page = getPageBySlugFromCurriculum(slug);
  if (!page) return null;

  const content = await getPageContent(page.id);
  return { title: page.title, content };
}
